site_name: MathWallet API Documentation
site_description: In Math We Trust!
site_author: MathWallet


site_url: http://doc.mathwallet.org/
repo_url: https://github.com/mathwallet/doc.mathwallet.org

dev_addr: 0.0.0.0:8000

copyright: Copyright &copy; 2018 MathWallet

pages:
    - Introduction: index.md
    - Blockchain:
        - EVM(ETH BNB etc): en/eth.md
        - Substrate(Polkadot etc): en/polkadot.md
        - Solana: en/solana.md
        - Arweave: en/ar.md
        - CosmosSDK: en/cosmos.md
        - Filecoin: en/filecoin.md
        - TRON: en/tron.md
        - Terra: en/terra.md
        - BinanceChain: en/binance.md
        - Near: en/near.md
        - EOS: en/eos.md
        - Nervos: en/nervos.md
    - Resources:
        - Logos&Assets: 'https://blog.mathwallet.org/?p=396'
        - FAQ: en/more.md

plugins:
    - search

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'indigo'
  logo: 'images/logo.svg'

extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/mathwallet'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/mathwallet'
